# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'googleSignPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for googleSignPOC
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

  target 'googleSignPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'googleSignPOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
