# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollPOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'SwipeViewController'


  # Pods for ScrollPOC

end
